name: Push Pack

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Compress pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Get previous tag
        id: get-previous-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
      - name: Get pack version from mcmeta
        id: lookupPackVersion
        run: echo "::set-output name=PACK_VERSION::$(jq -r .pack.version pack.mcmeta)"
      - name: Install pngquant
        run: sudo apt-get install -y pngquant libpng-dev
      - name: Minify Images
        continue-on-error: true
        run: find . -type f -name '*.png' -exec pngquant --strip -f --ext .png {} \; 2>/dev/null
      - name: Compress Pack
        run: zip -8 -r -X  pack.zip *
      - name: generate pack release
        env:
          BEGIN_COMMIT: ${{ steps.get-previous-tag.outputs.tag }}
          END_COMMIT: ${{ steps.lookupPackVersion.outputs.PACK_VERSION }}
        run: git fetch --tags --force && git log --pretty=format:"* %s (%h)" ${BEGIN_COMMIT}..${END_COMMIT} > release_notes.md
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: pack.zip
          allowUpdates: true
          bodyFile: "release_notes.md"
          draft: false
          prerelease: false
          tag: ${{ steps.lookupPackVersion.outputs.PACK_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
